baseURL = "https://zpaszportem.pl/"
languageCode = "pl-PL"
title = "Z Paszportem.pl"
theme = "blank"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      linkify = false      

[permalinks]
    "/" = "/index"

[menu]
    [[menu.main]]
    name = "O stronie"
    url = "/o-stronie"
    weight = 1
